apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-mentorservice
  labels:
    app: vision-mentorservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vision-mentorservice
  template:
    metadata:
      labels:
        app: vision-mentorservice
    spec:
      containers:
      - name: vision-mentorservice
        image: gcr.io/first-planet-444914-p6/vision-mentorservice:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mentor-db-credentials
              key: connectionString