apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-adminservice
  labels:
    app: vision-adminservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vision-adminservice
  template:
    metadata:
      labels:
        app: vision-adminservice
    spec:
      containers:
      - name: vision-adminservice
        image: gcr.io/first-planet-444914-p6/vision-adminservice:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: admin-db-credentials
              key: connectionString
