version: '3.8'

networks:
  vision-network:
    driver: bridge

services:
  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "4000:4000" 
    depends_on:
      - rabbitmq
      - user-service
      - mentor-service
      - admin-service
      - course-service
      - payment-service
      - messaging-service
    networks:
      - vision-network

  # User Service
  user-service:
    image: bahirk/vision-userservice
    build:
      context: ./services/userService
    container_name: user-service
    ports:
      - "4001:4001"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - vision-network

  # Mentor Service
  mentor-service:
    image: bahirk/vision-mentorservice
    build:
      context: ./services/mentorService
    container_name: mentor-service
    ports:
      - "4002:4002"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - vision-network

  # Admin Service
  admin-service:
    image: bahirk/vision-adminservice
    build:
      context: ./services/adminService
    container_name: admin-service
    ports:
      - "4003:4003"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - vision-network

  # Course Service
  course-service:
    image: bahirk/vision-courseservice
    build:
      context: ./services/courseService
    container_name: course-service
    ports:
      - "4004:4004"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - vision-network

  # Payment Service
  payment-service:
    image: bahirk/vision-paymentservice
    build:
      context: ./services/paymentService
    container_name: payment-service
    ports:
      - "4005:4005"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - vision-network

  # Messaging Service
  messaging-service:
    image: bahirk/vision-messagingservice
    build:
      context: ./services/messagingService
    container_name: messaging-service
    ports:
      - "4006:4006"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - vision-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vision-network
