apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-paymentservice
  labels:
    app: vision-paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vision-paymentservice
  template:
    metadata:
      labels:
        app: vision-paymentservice
    spec:
      containers:
      - name: vision-paymentservice
        image: gcr.io/first-planet-444914-p6/vision-paymentservice:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: payment-db-credentials
              key: connectionString
