apiVersion: v1
kind: Service
metadata:
  name: vision-messagingservice
spec:
  type: ClusterIP
  selector:
    app: vision-messagingservice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
