apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-courseservice
  labels:
    app: vision-courseservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vision-courseservice
  template:
    metadata:
      labels:
        app: vision-courseservice
    spec:
      containers:
      - name: vision-courseservice
        image: gcr.io/first-planet-444914-p6/vision-courseservice:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: course-db-credentials
              key: connectionString
