name: CI/CD Pipeline

on:
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - userService
          - mentorService
          - adminService
          - courseService
          - paymentService
          - messagingService
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ${{ matrix.service }}
        run: |
          SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
          docker build -t bahirk/vision-$SERVICE_NAME:latest ./backend/services/${{ matrix.service }}
          docker push bahirk/vision-$SERVICE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        service:
          - user-service
          - mentor-service
          - admin-service
          - course-service
          - payment-service
          - messaging-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Replace the current GKE setup with these steps
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'vision-cluster1'
          location: 'asia-south1-a'
          project_id: 'first-planet-444914-p6'

      - name: Deploy ${{ matrix.service }}
        run: |
          SERVICE_NAME=${{ matrix.service }}
          kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=bahirk/vision-${SERVICE_NAME//-}:latest
          kubectl rollout status deployment/${SERVICE_NAME}
