name: CI/CD Pipeline

on:
  push:
    branches:
      - deployment
  pull_request:
    branches:
      - deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - userService
          - mentorService
          - adminService
          - courseService
          - paymentService
          - messagingService
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ${{ matrix.service }}
        run: |
          docker build -t bahirk/vision-${{ matrix.service | toLowerCase }}:latest ./services/${{ matrix.service }}
          docker push bahirk/vision-${{ matrix.service | toLowerCase }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        service:
          - user-service
          - mentor-service
          - admin-service
          - course-service
          - payment-service
          - messaging-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GKE context
        run: |
          echo ${{ secrets.GKE_KUBECONFIG }} | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Verify Kubernetes context
        run: kubectl config current-context

      - name: Deploy ${{ matrix.service }}
        run: |
          kubectl set image deployment/${{ matrix.service }} ${{ matrix.service }}=bahirk/vision-${{ matrix.service }}:latest
          kubectl rollout status deployment/${{ matrix.service }}
